/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/plan/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Plan */
        post: operations["generate_plan_guide_plan_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/plan/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_guide_plan__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/periodic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Periodic */
        post: operations["periodic_guide_periodic_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_guide_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_guide_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/analyze/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Stream */
        post: operations["analyze_stream_guide_analyze_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_guide_session_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Feedback */
        post: operations["post_feedback_guide_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guide/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schemas
         * @description クライアント型生成専用 (openapi-typescript で拾う)。実呼び出し不要。
         */
        get: operations["_schemas_guide_schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description パイプラインメトリクス (インメモリ、dev/LT用).
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_analyze_guide_analyze_post */
        Body_analyze_guide_analyze_post: {
            /** File */
            file: string;
            /** Trigger Word */
            trigger_word: string;
            /**
             * Goal
             * @default
             */
            goal: string;
        };
        /** Body_analyze_stream_guide_analyze_stream_post */
        Body_analyze_stream_guide_analyze_stream_post: {
            /** File */
            file: string;
            /** Trigger Word */
            trigger_word: string;
            /**
             * Goal
             * @default
             */
            goal: string;
        };
        /** Body_chat_guide_chat_post */
        Body_chat_guide_chat_post: {
            /** File */
            file?: string | null;
            /** User Message */
            user_message: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /**
             * Stage1 Result
             * @default
             */
            stage1_result: string;
        };
        /** Body_periodic_guide_periodic_post */
        Body_periodic_guide_periodic_post: {
            /** File */
            file: string;
            /** Session Id */
            session_id: string;
            /**
             * Is Calibration
             * @default false
             */
            is_calibration: string;
            /**
             * Stage1 Result
             * @default
             */
            stage1_result: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Target Type */
            target_type: string;
            /** Sentiment */
            sentiment: string;
            /** Source */
            source: string;
            /**
             * Target Id
             * @default
             */
            target_id: string;
            /**
             * Target Content
             * @default
             */
            target_content: string;
            /**
             * Raw Content
             * @default
             */
            raw_content: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /** Step Index */
            step_index?: number | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Feedback Id */
            feedback_id: string;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** GuideResponse */
        GuideResponse: {
            /** Instruction */
            instruction: string;
            /** Reference Image Url */
            reference_image_url?: string | null;
            /** Current Step */
            current_step?: number | null;
            /** Total Steps */
            total_steps?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlanGenerateRequest */
        PlanGenerateRequest: {
            /** Goal */
            goal: string;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /**
             * Session Id
             * @default
             */
            session_id: string;
            /** Steps */
            steps: components["schemas"]["PlanStepResponse"][];
        };
        /** PlanStepResponse */
        PlanStepResponse: {
            /** Step Number */
            step_number: number;
            /** Text */
            text: string;
            /** Visual Marker */
            visual_marker: string;
            /** Frame Url */
            frame_url: string;
        };
        /**
         * SchemaExports
         * @description クライアント型生成用の束ね箱。中身は使わず、OpenAPI に型を載せるだけ。
         */
        SchemaExports: {
            stage1: components["schemas"]["Stage1Output"];
            stage_event: components["schemas"]["StageEvent"];
        };
        /** SessionStartResponse */
        SessionStartResponse: {
            /** Session Id */
            session_id: string;
        };
        /**
         * Stage1Output
         * @description Stage 1 (fast judgment) 構造化出力.
         */
        Stage1Output: {
            /**
             * Judgment
             * @description continue: 変化なし, next: ステップ進行, anomaly: 異常検知
             * @default continue
             * @enum {string}
             */
            judgment: "continue" | "next" | "anomaly";
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /**
             * Message
             * @description ユーザーへの応答。不要なら空文字。
             * @default
             */
            message: string;
            /**
             * Can Handle
             * @description Stage1 で完結できるか。False なら Stage2 にエスカレーション。
             * @default true
             */
            can_handle: boolean;
            /**
             * Escalation Reason
             * @description can_handle=False の場合の理由 (Stage2 が参照)。
             * @default
             */
            escalation_reason: string;
        };
        /**
         * StageEvent
         * @description /periodic / /chat の SSE `event: stage` ペイロード。
         */
        StageEvent: {
            /**
             * Stage
             * @enum {integer}
             */
            stage: 1 | 2;
            /** Judgment */
            judgment: string;
            /** Confidence */
            confidence: number;
            /** Message */
            message: string;
            /** Blocks */
            blocks: {
                [key: string]: unknown;
            }[];
            /** Escalated */
            escalated: boolean;
            /** Current Step Index */
            current_step_index?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generate_plan_guide_plan_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_guide_plan__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    periodic_guide_periodic_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_periodic_guide_periodic_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_guide_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_chat_guide_chat_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_guide_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_guide_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_stream_guide_analyze_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_stream_guide_analyze_stream_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_guide_session_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStartResponse"];
                };
            };
        };
    };
    post_feedback_guide_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _schemas_guide_schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaExports"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
